#!/bin/sh
# husky

# Created by Husky v4.3.8 (https://github.com/typicode/husky#readme)
#   At: 10/4/2023, 4:04:19 PM
#   From: /home/midilab/projects/headless-cms/tinasaurus/node_modules/husky (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
